services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green_hive_app
    restart: always
    ports:
      - '4000:4000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: green_hive_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local